env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
  - prettier
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
  arrow-body-style: 0
  prefer-arrow-callback: 0
  no-underscore-dangle: 0
  import/no-unresolved: 2
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
      - .js
      - .jsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node:
      extensions:
        - .ts
        - .tsx
        - .js
        - .jsx

